### ISSUE TITLE
elixir 如何使用这个库？

### ISSUE THREAD

**Issue by szh111123** [zmstone/snappyer#13]
你好 我解析.proto文件时 发现prometheus 使用snappy 压缩了 请问elixir 如何使用 当前这个库啊

**Comment by zmstone** [comment]
add this lib as dependency  `{:snappyer, "~> 1.2"}` to your mix file
and call `:snappyer.decompress(compressed)` in the code.

**Comment by zmstone** [comment]
https://elixirschool.com/en/lessons/intermediate/erlang
